author:
        name: Microsoft

description: Use SQL Server 2017 + R Services to build and deploy a machine learning model for loan credit risk.

# site variables
solution_name: Loan Credit Risk 
folder_name: Loans
db_name: Loans
ps1_name: Loan_Credit_Risk.ps1
image_url: images/loan.jpg
jupyter_name: Loan_Credit_Risk_Notebook.ipynb

cig_text: SQL Server 2017 on Azure
onp_text: SQL Server 2017 On-Prem 
hdi_text: HDInsight Spark 

# urls, etc
code_url: "https://github.com/Microsoft/r-server-loan-credit-risk"
website_url: "https://microsoft.github.io/r-server-loan-credit-risk"  
deploy_url: "https://aka.ms/loan-credit-risk" 
deploy_url_hdi: "https://aka.ms/loan-credit-risk-hdi" 
pbix_name: LoanCreditRisk.pbix
hdipbix_name: "LoanCreditRisk HDI.pbx"
pbix_hdidownload_url: "https://github.com/Microsoft/r-server-loan-credit-risk/blob/master/LoanCreditRisk%20HDI.pbix"
pbix_sqldownload_url: "https://github.com/Microsoft/r-server-loan-credit-risk/blob/master/LoanCreditRisk.pbix"
pbix_view_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/loancreditrisk"
pbix_hdiview_url: "https://start.cortanaintelligence.com/TryItNow/Dashboard/loancreditriskhdi"
