author:
        name: Microsoft

description: Use SQL Server 2016 + R Services to build and deploy a machine learning model for loan credit risk.

# site variables
solution_name: Loan Credit Risk 
folder_name: Loans
db_name: Loans
ps1_name: Loan_Credit_Risk.ps1
image_url: images/loan.jpg

cig_text: SQL Server 2016 on Azure
onp_text: SQL Server 2016 On-Prem 
hdi_text: HDInsight Spark 

# urls, etc
code_url: "https://github.com/Microsoft/r-server-loan-credit-risk"
website_url: "https://microsoft.github.io/r-server-loan-credit-risk"  
dashboard_url: "LINKHERE"
deploy_url: "http://aka.ms/loan-credit-risk" 
deploy_url_hdi: "LINKHERE"
pbix_hdidownload_url: "LINKHERE"
pbix_sqldownload_url: "LINKHERE"
pbix_view_url: "LINKHERE"

